### ISSUE TITLE
Regression in Simplify translation since KeY 1.4

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1000]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1000) where the discussions are preserved.
    
----
    
* Mantis: [MT-1045](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1045)
* Submitted on: 2010-11-24 by (at)bweiss
* Updated: 2011-03-25

### Description

> Simplify cannot close some problems any more which it used to be able to close in KeY 1.4, and which both Z3 and Yices can close without problems.

### Steps to reproduce

```
Load the attached file "simplify.key", then send the sequent to Simplify. In KeY 1.4, the proof closes; in current KeY, it does not.

(Also: Load the attached file Exercise7.java, and prove "EnsuresPost" for the "insert" method. Switch "quantifier instantiation" to "none" and run the strategy to completion. Then send the remaining goals to Simplify, and compare which goals are closed using KeY 1.4 and current KeY.)
```

### Additional Information

```
Distilled out of a problem report by Wolfgang Schreiner, RISC Linz:

"You might be interested that I just noticed in the last version
1.6.0 a regression with respect to version 1.4.0. For the attached
source of a JML-annotated insertion-sort program, in 1.4.0
the proof of condition "EnsuresPost" worked automatically
for both functions insert() (about 4 repeated applications
of the automatic strategy and Simplify) and sort() (about
8 repeated applications).

However, none of the proofs works with version 1.6.0 any more."
```

## Files

  
[simplify.key](/uploads/4bd52f076774491e97bad5bc0ff20390/simplify.key)
  

  
`Exercise7.java`:

```java
public class Exercise7
{
  /*@ public normal_behavior
    @ requires a != null && 0 <= n && n < a.length;
    @ requires (\forall int j; 0 <= j && j < n-1; a[j] <= a[j+1]);
    @ assignable a[*];
    @ ensures (\forall int j; n < j && j < a.length; a[j] == \old(a[j]));
    @ ensures (\forall int j; 0 <= j && j < n; a[j] <= a[j+1]);
    @ ensures (\exists int p; 0 <= p && p <= n; 
    @   (\forall int j; 0 <= j && j < p; a[j] == \old(a[j])) &&
    @   a[p] == \old(a[n]) &&
    @   (\forall int j; p < j && j <= n; a[j] == \old(a[j-1])));
  */
  public static void insert(int[] a, int n)
  {
    int i = n;
    int t = a[i];
    /*@ loop_invariant 
      @   a != null && 0 <= n && n < a.length &&
      @   (\forall int j; 0 <= j && j < n-1; \old(a[j]) <= \old(a[j+1])) &&
      @   0 <= i && i <= n && t == \old(a[n]) &&
      @   (\forall int j; n < j && j < a.length; a[j] == \old(a[j])) &&
      @   (\forall int j; 0 <= j && j <= i; a[j] == \old(a[j])) &&
      @   (\forall int j; i < j && j <= n; a[j] > t && a[j] == \old(a[j-1]));
      @ assignable a[*], i;
      @ decreases i;
      (at)*/
    while (i > 0 && a[i-1] > t)
    {
      a[i] = a[i-1];
      i = i-1;
    }
    a[i] = t;
  }

  /*@ public normal_behavior
    @ requires a != null;
    @ assignable a[*];
    @ ensures (\forall int j; 0 <= j && j < a.length-1; a[j] <= a[j+1]);
    (at)*/
  public static void sort(int[] a)
  {
    int i = 0;
    int n = a.length;
    /*@ loop_invariant 
      @   a != null && n == a.length &&
      @   0 <= i && i <= n &&
      @   (\forall int j; 0 <= j && j < i-1; a[j] <= a[j+1]);
      @ assignable a[*], i;
      @ decreases n-i;
      (at)*/
    while (i < n)
    {
      insert(a, i);
      i = i+1;
    }
  }
}

```

## Notes

_(at)rbubel at 2010-11-24_
> Just an observation: It works if the proof-independent taclet translation is switched on.

_(at)bweiss at 2010-11-24_
> Ah, thanks, that's interesting. I'll send Wolfgang an e-mail about the whole thing in a minute.

_(at)bweiss at 2010-11-24_
> Actually, switching on the proof-independent taclet translation makes it work *too* well. I see another bug report coming.

_(at)bweiss at 2010-11-24_
> See also #1046.

_(at)niederma at 2011-03-25_
> Even after extensive investigations I could not find out how to solve this problem. Since KeY 1.4 uses another implementation for the simplify translation the resulting translations can not be compared easily. 
> Probably it would be very helpful to have some good documentation about Simplify.

## History

* (at)bweiss -- (`NEW_BUG`) _2010-11-24_

* (at)bweiss -- (`FILE_ADDED`) _2010-11-24_

* (at)bweiss -- (`FILE_ADDED`) _2010-11-24_

* (at)rbubel -- (`BUGNOTE_ADDED`) _2010-11-24_

* (at)bweiss -- (`BUGNOTE_ADDED`) _2010-11-24_

* (at)bweiss -- (`BUGNOTE_ADDED`) _2010-11-24_

* (at)bweiss -- (`BUGNOTE_ADDED`) _2010-11-24_

* (at)niederma -- (`NORMAL_TYPE`) _2011-02-01_

* (at)niederma -- (`NORMAL_TYPE`) _2011-02-01_

* (at)bweiss -- (`NORMAL_TYPE`) _2011-02-07_

* (at)bweiss -- (`NORMAL_TYPE`) _2011-02-07_

* (at)niederma -- (`NORMAL_TYPE`) _2011-03-24_

* (at)niederma -- (`NORMAL_TYPE`) _2011-03-24_

* (at)niederma -- (`BUGNOTE_ADDED`) _2011-03-25_

* (at)niederma -- (`NORMAL_TYPE`) _2011-03-25_

* (at)bweiss -- (`NORMAL_TYPE`) _2011-03-25_

## Attributes

* Category: SMT
* Status: NEW
* Severity: MAJOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: ALWAYS
* Platform: 
* Commit: None
* Build: b31a1545c7c350992160fa28600249a1
* Tags []
* Labels:  ~SMT  ~Bug  ~NORMAL  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1045)
    
----
    
Information: 
* created_at: 2017-05-29T02:53:24.185Z
* updated_at: 2017-05-29T02:53:24.547Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by mattulbrich** [comment]
Support for Simplify has been abandon a while ago.
