### ISSUE TITLE
Missing support for mod in SMT translation

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1010]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1010) where the discussions are preserved.
    
----
    
* Mantis: [MT-1047](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1047)
* Submitted on: 2010-11-26 by (at)bweiss
* Updated: 2012-12-07

### Description

> Currently, the translations to SMT-LIB and to Simplify cannot handle KeY's integer modulo operator.
> 
> When fixing this, care must be taken because it may be that rounding is defined differently in KeY than in SMT-LIB and/or in Simplify.

### Steps to reproduce

```
Try to verify the attached program by running the strategy and then calling Z3.
```

## Files

  
`RussM.java`:

```java
import java.io.*;

public class RussM{

static int a,a1;
static int b,b1;
static int z1 = 0;
    static int x,y;

     /*(at)
      @ public normal_behavior
      @ requires b>= 0 && b<= 45000;
      @ requires (a>=0)?(a<=45000):(-a<=45000);
      @ ensures \result == a * b;
      @ diverges true;
      (at)*/
    public static int russm(int a, int b) {
      int z = 0;
      x = a;
      y = b;
	/*@ loop_invariant  a*b + z == x*y && b>=0;
	  @ assignable a, b, z;
	  (at)*/
      while (b!=0){
     if  ((b / 2) * 2 == b) 
       {a = 2*a;
        b = b / 2;}
      else
        {z = z + a;
         a = 2*a;
          b = b / 2;
	}
      };
      return z;
    }

}

```

## Associated Bugs

* Relates to MT-1245 with 

## History

* (at)bweiss -- (`NEW_BUG`) _2010-11-26_

* (at)bweiss -- (`FILE_ADDED`) _2010-11-26_

* (at)niederma -- (`NORMAL_TYPE`) _2011-02-01_

* (at)niederma -- (`NORMAL_TYPE`) _2011-02-01_

* (at)niederma -- (`NORMAL_TYPE`) _2011-03-25_

* (at)bweiss -- (`NORMAL_TYPE`) _2011-03-25_

* (at)grahl -- (`BUG_ADD_RELATIONSHIP`) _2012-11-23_

* (at)grahl -- (`NORMAL_TYPE`) _2012-12-07_

* (at)grahl -- (`DESCRIPTION_UPDATED`) _2012-12-07_

* (at)grahl -- (`NORMAL_TYPE`) _2012-12-07_

## Attributes

* Category: SMT
* Status: NEW
* Severity: FEATURE
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: LOW
* Reproducibility: ALWAYS
* Platform: 
* Commit: None
* Build: b31a1545c7c350992160fa28600249a1
* Tags []
* Labels:  ~SMT  ~Feature  ~LOW  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1047)
    
----
    
Information: 
* created_at: 2017-05-29T02:53:54.704Z
* updated_at: 2022-01-21T20:48:20.610Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 1

**Comment by FliegendeWurst** [comment]
Works in new KeY
