### ISSUE TITLE
The interactive prover sometimes looses the focused goal

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1030]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1030) where the discussions are preserved.
    
----
    
* Mantis: [MT-1168](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1168)
* Submitted on: 2012-02-09 by (at)scheben
* Updated: 2013-07-18

### Description

> The interactive prover sometimes looses the focused goal. This results in a NullPointerException. It occurs normally only in long and complex proofs with a lot of interaction...
> 
> java.lang.NullPointerException
>         at de.uka.ilkd.key.gui.InteractiveProver.getInteractiveRuleAppIndex(InteractiveProver.java:272)
>         at de.uka.ilkd.key.gui.InteractiveProver.getBuiltInRule(InteractiveProver.java:257)
>         at de.uka.ilkd.key.gui.KeYMediator.getBuiltInRule(KeYMediator.java:509)
>         at de.uka.ilkd.key.gui.nodeviews.SequentViewListener.mouseClicked(SequentViewListener.java:145)
>         at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:253)
>         at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:252)
>         at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:252)
>         at java.awt.Component.processMouseEvent(Component.java:6291)
>         at javax.swing.JComponent.processMouseEvent(JComponent.java:3267)
>         at java.awt.Component.processEvent(Component.java:6053)
>         at java.awt.Container.processEvent(Container.java:2041)
>         at java.awt.Component.dispatchEventImpl(Component.java:4651)
>         at java.awt.Container.dispatchEventImpl(Container.java:2099)
>         at java.awt.Component.dispatchEvent(Component.java:4481)
>         at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4577)
>         at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4247)
>         at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4168)
>         at java.awt.Container.dispatchEventImpl(Container.java:2085)
>         at java.awt.Window.dispatchEventImpl(Window.java:2478)
>         at java.awt.Component.dispatchEvent(Component.java:4481)
>         at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:643)
>         at java.awt.EventQueue.access$000(EventQueue.java:84)
>         at java.awt.EventQueue$1.run(EventQueue.java:602)
>         at java.awt.EventQueue$1.run(EventQueue.java:600)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
>         at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
>         at java.awt.EventQueue$2.run(EventQueue.java:616)
>         at java.awt.EventQueue$2.run(EventQueue.java:614)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
>         at java.awt.EventQueue.dispatchEvent(EventQueue.java:613)
>         at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
>         at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
>         at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
>         at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
>         at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
>         at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

## Notes

_(at)grahl at 2013-07-18_
> Any way to reproduce this?

## History

* (at)scheben -- (`NEW_BUG`) _2012-02-09_

* (at)grahl -- (`BUGNOTE_ADDED`) _2013-07-18_

* (at)grahl -- (`NORMAL_TYPE`) _2013-07-18_

## Attributes

* Category: GUI
* Status: FEEDBACK
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: HAVENOTTRIED
* Platform: 
* Commit: None
* Build: 
* Tags []
* Labels:  ~GUI  ~Bug  ~NORMAL  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1168)
    
----
    
Information: 
* created_at: 2017-05-29T02:54:26.127Z
* updated_at: 2017-05-29T02:54:26.127Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
No reproduction in 10 years => close
