### ISSUE TITLE
KeY GUI opens with tiny window size after fresh installation

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#104]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/104) where the discussions are preserved.
    
----
    
* Mantis: [MT-1431](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1431)
* Submitted on: 2014-04-30 by (at)stijn
* Updated: 2014-04-30

### Description

> When I run startprover, the terminal reports the following warning:
> 
> KeY Version 2.2.0 (internal: ff533867532ab7096e0a6d25d7cc3bce9fc9e640)
> ? Copyright 2001û2013 Karlsruhe Institute of Technology, Chalmers University of
> Technology, and Technische Universit?t Darmstadt
> KeY is protected by the GNU General Public License
> 
> Using assertions ...
> apr 30, 2014 10:03:50 AM java.util.prefs.WindowsPreferences <init>
> WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0
> x80000002. Windows RegCreateKeyEx(...) returned error code 5.
> 
> 
> KeY then opens, but apparently it defaults to window size 0, so a manual resize of the window is necessary to see the GUI properly.

### Steps to reproduce

```
Do a fresh installation and run startProver
```

## Notes

_(at)mulbrich at 2014-04-30_
> Thanks for the report.
> 
> What OS are you using?
> Had KeY been installed on that system already before?

_(at)stijn at 2014-04-30_
> It's windows 8 and KeY hasn't been installed before on that system (well, it has on Linux but not on Windows).

## History

* (at)stijn -- (`NEW_BUG`) _2014-04-30_

* (at)mulbrich -- (`BUGNOTE_ADDED`) _2014-04-30_

* (at)stijn -- (`BUGNOTE_ADDED`) _2014-04-30_

## Attributes

* Category: GUI
* Status: NEW
* Severity: MINOR
* OS: 8
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: HAVENOTTRIED
* Platform: 
* Commit: ff533867532ab7096e0a6d25d7cc3bce9fc9e640
* Build: 
* Tags []
* Labels:  ~GUI  ~Bug  ~NORMAL  
* Version: _2.2_ 

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1431)
    
----
    
Information: 
* created_at: 2017-05-29T02:29:25.088Z
* updated_at: 2017-05-29T02:29:25.364Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
Fixed
