### ISSUE TITLE
cannot access the length of a sequence in a JML ghost assignment

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1110]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1110) where the discussions are preserved.
    
----
    
* Mantis: [MT-1091](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1091)
* Submitted on: 2011-05-04 by (at)grahl
* Updated: 2011-07-07

### Description

> Ghost or model field references are not known to RecodeR if they are postfixed with .length (all other references are fine, as are Java arrays).

## Files

  
[Test.java](/uploads/4b758687b9ceb47544aaa6c81d61c73f/Test.java)
  

## History

* (at)grahl -- (`NEW_BUG`) _2011-05-04_

* (at)grahl -- (`NORMAL_TYPE`) _2011-05-04_

* (at)grahl -- (`NORMAL_TYPE`) _2011-05-04_

* (at)grahl -- (`FILE_ADDED`) _2011-05-04_

* (at)grahl -- (`BUG_ADD_RELATIONSHIP`) _2011-05-20_

* (at)grahl -- (`NORMAL_TYPE`) _2011-07-07_

* (at)grahl -- (`NORMAL_TYPE`) _2011-07-07_

* (at)grahl -- (`NORMAL_TYPE`) _2014-01-03_

## Attributes

* Category: JML (semantics)
* Status: ACKNOWLEDGED
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: ALWAYS
* Platform: 
* Commit: None
* Build: 
* Tags []
* Labels:  ~JML (Semantics)  ~Bug  ~NORMAL  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1091)
    
----
    
Information: 
* created_at: 2017-05-29T02:56:24.220Z
* updated_at: 2017-05-29T02:56:24.220Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
Works if you use `//@ set y = \seq_length(x);`
