### ISSUE TITLE
Rules for things like int a = b | c; are not properly matched (for intRules.key)

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#122]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/122) where the discussions are preserved.

                ----

                * Mantis: [MT-266](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=266)
* Submitted on: 2004-01-28 by @most
* Updated: 2004-01-29

* Assigned to: @aroth

### Description

> The rules for an expression int a = b | c; is not properly matched. b and c are ints, but the rule for booleans is matched and not the rule assignment_binary_OR_1 from intRules.key

### Steps to reproduce

```
Try the attached file in Together.
```

## Files

  
[0266-Class1.java](/uploads/6c86a8ec465fe9382bd366c9213e7d8a/0266-Class1.java)
  

## Notes

_@aroth at 2004-01-28_
> Fixed in 0.891.

## History

* @most -- (`NEW_BUG`) _2004-01-28_

* @most -- (`FILE_ADDED`) _2004-01-28_

* @aroth -- (`NORMAL_TYPE`) _2004-01-28_

* @aroth -- (`NORMAL_TYPE`) _2004-01-28_

* @aroth -- (`NORMAL_TYPE`) _2004-01-28_

* @aroth -- (`NORMAL_TYPE`) _2004-01-28_

* @aroth -- (`BUGNOTE_ADDED`) _2004-01-28_

* @most -- (`NORMAL_TYPE`) _2004-01-29_

## Attributes

* Category: Prover Core
* Status: CLOSED
* Severity: MAJOR
* OS: 
* Target Version: 
* Resolution: FIXED
* Priority: HIGH
* Reproducibility: ALWAYS
* Platform: 
* Commit: None
* Build: 888
* Tags []
* Labels:  ~Prover Core  ~Bug  ~HIGH  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=266)

                ----

                Information: 
                    * created_at: 2017-05-29T02:29:46.327Z
                    * updated_at: 2017-05-29T02:29:46.750Z
                    * closed_at: 2017-05-29T02:29:46.712Z  (closed_by: )
                    * milestone: 
                    * user_notes_count: 0

**Comment by aroth** [comment]
I'm getting emails & notifications for all these projects with @aroth from your organization flagged.
