### ISSUE TITLE
rules for autoboxing

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1270]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1270) where the discussions are preserved.

                ----

                * Mantis: [MT-1509](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1509)
* Submitted on: 2014-11-19 by @grahl
* Updated: 2014-11-20

### Description

> Since Java 5, there is a feature called "autoboxing" that allows to convert primitive values to an object representation and back.
> 
> Integer i = 5;
> 
> is legal Java 5 and stands for
> 
> Integer i = Integer.valueOf(5);
> 
> and
> 
> int z = intObj;
> 
> stands for
> 
> int z = intObj.intValue();
> 
> There should be rules for this as described in Mattias' diploma thesis.

### Additional Information

```
Currently KeY raises an exception during symbolic execution.

Building a term failed. Normally there is an arity mismatch or one of the subterms' sorts is not compatible (e.g. like the '2' in "true & 2")
The top level operator was elem-update(result)(Sort: Update); its expected arg sorts were:
1.) sort: java.lang.Integer, sort hash: 1926898485

The subterms were:
1.) Z(5(#))(sort: int, sort hash: 1215648458)
```

## Notes

_@mulbrich at 2014-11-20_
> To make autoboxing more transparent, I would propose to implement a
> transformation that replaces these implicit method calls by their
> explicit counterparts prior to loading it in KeY.
> 
> There may even exist such a transformation in recoder already.

## History

* @grahl -- (`NEW_BUG`) _2014-11-19_

* @mulbrich -- (`BUGNOTE_ADDED`) _2014-11-20_

## Attributes

* Category: Calculus
* Status: NEW
* Severity: FEATURE
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: LOW
* Reproducibility: NOTAPPLICABLE
* Platform: 
* Commit: e2148a409fd9ff120bcb64631b51c456c8cca3c9
* Build: 
* Tags []
* Labels:  ~Calculus  ~Feature  ~LOW  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1509)

                ----

                Information: 
                    * created_at: 2017-05-29T03:01:19.979Z
                    * updated_at: 2017-06-28T17:23:58.484Z
                    * closed_at: 2017-06-28T17:23:33.693Z  (closed_by: )
                    * milestone: 
                    * user_notes_count: 1

**Comment by FliegendeWurst** [comment]
Reopening this issue, since it was not resolved. Using autoboxing still leads to the same exception:

```java
class Autobox {
    /*@ ensures \result != null;
      @*/
    Integer testing() {
        return 5;
    }
}
```
