### ISSUE TITLE
Pretty-printing of method-frames unusable

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1377]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1377) where the discussions are preserved.
    
----
    
* Mantis: [MT-1518](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1518)
* Submitted on: 2014-12-13 by (at)klebanov
* Updated: 2014-12-13

### Description

> There should be a line break after the opening method-frame brace. Currently, the situation looks like this:
````
 \<{try {method-frame(source=main(java.lang.String[])(at)org.apache.harmony.security.provider.crypto.SHA1PRNG_SecureRandomImpl): { {method-frame(source=<init>()(at)org.apache.harmony.security.provider.crypto.SHA1PRNG_SecureRandomImpl,this=s): { {throw new java.lang.NegativeArraySizeException ();
````
> 
> This is a 289-character-long line.
> 
> A minor complaint is also that package prefixes are printed in the method-frame even though I have set the "hide package prefix" toggle.

## History

* (at)klebanov -- (`NEW_BUG`) _2014-12-13_

* (at)grahl -- (`BUG_ADD_RELATIONSHIP`) _2014-12-19_

## Attributes

* Category: GUI
* Status: NEW
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: ALWAYS
* Platform: 
* Commit: 7f4d3f4f3d1b6d9ca6c0c11be535c7bfa8d736c2
* Build: 
* Tags []
* Labels:  ~GUI  ~Bug  ~NORMAL  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1518)
    
----
    
Information: 
* created_at: 2017-05-29T03:04:28.516Z
* updated_at: 2021-06-21T23:46:11.716Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
Fixed in recent KeY
