### ISSUE TITLE
Interactively applied built in rules are not marked with the icon for interactive rule application (hand)

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1409]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1409) where the discussions are preserved.
    
----
    
* Mantis: [MT-1450](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1450)
* Submitted on: 2014-06-03 by (at)mhentschel
* Updated: 2014-10-06

### Description

> Interactively applied taclets are marked with the hand icon. 
> Built in rules should behave on the same way.

### Steps to reproduce

```
Apply a built in rule interactively.
```

## History

* (at)mhentschel -- (`NEW_BUG`) _2014-06-03_

* (at)grahl -- (`NORMAL_TYPE`) _2014-10-06_

## Attributes

* Category: GUI
* Status: NEW
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: ALWAYS
* Platform: 
* Commit: 70c8e114de4c8c3c96251b004f784018e8af857f
* Build: 
* Tags []
* Labels:  ~GUI  ~Bug  ~NORMAL  
* Version: _2.2_ 

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1450)
    
----
    
Information: 
* created_at: 2017-05-29T03:05:37.088Z
* updated_at: 2017-06-12T14:50:16.647Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
This is done consistently in recent KeY versions.
