### ISSUE TITLE
Gracefully handle syntax errors in model methods

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1485]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1485) where the discussions are preserved.
    
----
    
 

## Description

Model methods are defined in JML comments, but are parsed as regular Java methods.
If a semi-colon is missing in the method definition, an error occurs.
However, the error message does not reflect that the problem is with
parsing the model method at a particular place in the source file.

## Reproducible
  
Load the following source file:

```
package linkedlist;
class Example {
	/*@ model_behavior
	  @ accessible this.*;
	  @ model boolean weird() { return true }
	  (at)*/
}
```

### Stack trace

```
de.uka.ilkd.key.java.ConvertException: String index out of range: -8
    at de.uka.ilkd.key.java.Recoder2KeY.reportError(Recoder2KeY.java:1321)
    at de.uka.ilkd.key.java.Recoder2KeY.recoderCompilationUnitsAsFiles(Recoder2KeY.java:421)
    at de.uka.ilkd.key.java.Recoder2KeY.readCompilationUnitsAsFiles(Recoder2KeY.java:359)
    at de.uka.ilkd.key.proof.init.ProblemInitializer.readJava(ProblemInitializer.java:314)
...
```

---

* KeY Version 2.7 (internal: 90bb886cd7b78027c8f6703803461f09e5699bb9)

* Component: /label ~"JML Parser" 

    
----
    
Information: 
* created_at: 2019-01-24T10:21:18.360Z
* updated_at: 2019-01-24T10:21:18.360Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
The error message looks acceptable in current KeY versions:
![image](https://user-images.githubusercontent.com/12560461/220671674-e842629f-8b6d-41f0-8c25-05f4c085edd1.png)
