### ISSUE TITLE
Remove Transformation-Based Loop Invariant Rule for v2.8

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1495]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1495) where the discussions are preserved.
    
----
    
# Summary

I propose to, for various reasons, remove the old transformation-based loop invariant rule from KeY for 2.8, and instead switch to loop scope-based taclets. For teaching, there should be a special variant strongly coupled to the main part of KeY (e.g., via an option) which still uses the old rule, but disallows most, if not all, kinds of irregular termination behavior (in loops). **UPDATE**: I found a sound and complete solution based on loop scopes which still has the three-branch structure and thus is suitable for teaching (in my opinion), see comment below.

# Problems of the Old Rule

The old loop invariant rule in KeY has several drawbacks:

1.  It is quite brittle in presence of irregular termination behavior (breaks, returns, exceptions, potentially nested in try-catch-finally blocks which complicate things), see e.g. https://git.key-project.org/key/key/issues/991, https://git.key-project.org/key/key/issues/1236, https://git.key-project.org/key/key/issues/676; probably, there are other things that might appear in the future. This is all due to the complexity of doing complex program transformations right.
2.  It is a big, old Moloch of plain Java code difficult to maintain, in addition to the intrinsic complexity of code transformations mentioned above
3.  It is intransparent in several ways:
    1.  It is very hard to write it down on paper. Also the version in the KeY book does not match the implementation (where already some bug fixes etc. had to be added).
    2.  It is hard to see what happens when looking at the code.
    3.  When applying it interactively, you are not presented a preview of the result in the popup which is shown before taclet applications
    4.  Returns, breaks and uncaught exceptions lead to proof obligations of the **post condition** (and not the invariant) in the "Preserved" branch generated from the rule.

# Alternatives

Meanwhile, the [*loop scope* approach](https://www.key-project.org/papers/loopscopes/) has been developed which deals with irregular termination transparently and efficiently (it solves 1, 3.1 and 3.4 above). Many of the bugs occurring for the transformation-based rule simply cannot occur in this approach, since irregular termination is contained within the scope and treated by very simple taclets only after the final reason for termination is fixed. Also, it is really easy to write down the loop scope invariant rule on paper and thus to document the state of KeY in a future version of / in additions to the KeY book.

Moreover, we recently also developed **taclets** for the loop scope method. This solves 2, 3.1 and 3.2 above. The Java code related to the taclets (hidden in variable conditions and transformers) is well-scoped and has clear responsibilities. The overall job of the taclet is furthermore easy to comprehend when just looking at the taclet syntax (at least, compared to plain Java code). At the bottom of this post, you find the loop scope taclet for while rules within the diamond modality (the box version does not contain the parts related to the variant reasoning). The taclet also supports transactions and permission-based reasoning. One additional advantage of having those taclets is that it is easy to create specialized rules for special purposes, like information flow or relational verification (I myself use one to prove correctness of refactorings). Thus, it is easier to separate additions to the KeY core from each other, and you have way less code duplication as when copying the whole Java class responsible for a loop invariant rule (variable conditions and transformers can mostly be re-used).

Therefore, I propose: **Remove the transformation-based loop invariant rule for KeY 2.8**.

That is, keep it in the code base to make old existing proofs load, but prevent it from being chosen by the strategies or being applied interactively.

# KeY for Teaching

**EDIT:** See my comment below for a sound and complete solution obtained by merging loop scopes with a three-branch approach.

There is one argument against this, mentioned to me by (at)mulbrich: KeY is used extensively in teaching, and there you might not want to introduce loop scopes and instead rely on the base case/step/use case reasoning of the transformation-based approach. This argument is of course valid. I propose two potential solutions, which would make sense to me:

1.  Introduce loop scopes in KeY lectures. It is not that difficult, and actually easier as explaining the complex transformations and flags in presence of irregular termination.
2.  Have a KeY variant *especially for teaching* which just makes the transformation superfluous by disallowing programs exposing that behavior. This variant should be incomplete, but sound. There are again several options here: One could create a KeY version for a stripped-down language, like KeY-Hoare. This would mean that probably that version would be decoupled from developments on the master (what also happened to KeY-ABS), therefore I would recommend another way: Disallowing irregular behavior (at least in loops) by, e.g., a taclet option. We currently can set programRules to Java or None, where the latter is sound, but incomplete. There could be a way between. Of course we still have exceptions in loops, even if we forbid breaks and returns, but those are usually only a problem in conjunction with the latter. Also, we could adapt the loop invariant rule to catch any exception in the body and halt execution (in some way) to even prevent exceptions in the loop (because of issue 3.4) above. Or, exceptional behavior should be described also by the loop invariant.

# Example Loop Scope Invariant Taclet

```
loopScopeInvDia {
  \schemaVar \formula inv;
  \schemaVar \term any variantTerm;
  \schemaVar \formula loopFormula;
  \schemaVar \program Variable #variant;
  
  \schemaVar \skolemTerm Heap anon_heap_LOOP; 
  \schemaVar \skolemTerm Heap anon_savedHeap_LOOP; 
  \schemaVar \skolemTerm Heap anon_permissions_LOOP; 
   
  \schemaVar \program Variable #heapBefore_LOOP; 
  \schemaVar \program Variable #savedHeapBefore_LOOP; 
  \schemaVar \program Variable #permissionsBefore_LOOP; 
   
  \find ( (\modality{#dia} {.. while (#nse) #body ... }\endmodality(post)) )

  \varcond(\new(#x, boolean))
  \varcond(\new(#variant, any))
  \varcond(\new(#heapBefore_LOOP, Heap))
  \varcond(\new(#savedHeapBefore_LOOP, Heap))
  \varcond(\new(#permissionsBefore_LOOP, Heap))
 
  \varcond(\not\hasLoopLabel) 
  \varcond(\storeTermIn(loopFormula, \modality{#dia}{ while (#nse) #body }\endmodality(post)))
  \varcond(\getInvariant(inv))
  \varcond(\getVariant(variantTerm))

  "Invariant Initially Valid":
    \replacewith(inv);

  "Invariant Preserved and Used":
    \replacewith (
      {   #createBeforeLoopUpdate(loopFormula, #heapBefore_LOOP, #savedHeapBefore_LOOP, #permissionsBefore_LOOP) 
       || #createLocalAnonUpdate(loopFormula)
       || #createHeapAnonUpdate(loopFormula, anon_heap_LOOP, anon_savedHeap_LOOP, anon_permissions_LOOP)}
        {#variant:=variantTerm}
          (inv ->
             (\modality{#dia}{
                ..
                boolean #x;
                #x = true;
                loop-scope(#x) {
                  if (#nse) { 
                    #body
                    #x = false;
                  }
                }
                ...
              }\endmodality(
                (#x<<loopScopeIndex>> = TRUE -> post) & 
                (#x<<loopScopeIndex>> = FALSE -> 
                    inv
                  & #createFrameCond(loopFormula, #heapBefore_LOOP, #savedHeapBefore_LOOP, #permissionsBefore_LOOP)
                  & prec(variantTerm, #variant))
               )))
    )
    
    \add (#wellFormedCond(loopFormula, anon_heap_LOOP, anon_savedHeap_LOOP, anon_permissions_LOOP) ==>)

  \heuristics(loop_scope_inv_taclet)
};
```

This should be interesting for (at least): (at)mulbrich, (at)rbubel, (at)reiner, (at)wasser, (at)beckert
    
----
    
Information: 
* created_at: 2019-04-09T12:26:25.853Z
* updated_at: 2021-11-10T13:21:10.689Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 48

**Comment by mattulbrich** [comment]
Let's keep it for a while. There are still a few mechanisms in KeY that require the 3-branch version of the loop invariant.
