### ISSUE TITLE
Statistics Dialog Size Explodes

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1534]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1534) where the discussions are preserved.
    
----
    
## Description

The dialog that shows the statistics at the end of the proof explodes if long taclet names are present. 
Long taclet names are often created dynamical for insert definitions etc...

![statsexplode](/uploads/e5a4796248725100754da84492acbf4a/statsexplode.png)

## Reproducible

Always. Just use a Java file with a long package name.
    
----
    
Information: 
* created_at: 2020-04-23T13:53:26.146Z
* updated_at: 2020-04-25T03:02:02.211Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 2

**Comment by FliegendeWurst** [comment]
Fixed in #3232 by limiting the maximum size
