### ISSUE TITLE
KeYCollections::filterAlphabetic only allows A-Z leading to use of fallback name x in many cases

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1639]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1639) where the discussions are preserved.
    
----
    
contradictionary to its javadoc `KeYCollections::filterAlphabetic` only allows A-Z and not a-z.
That leads to usage of the x fallback in `VariableNamer` more often than nessasary.

As [KeYCollections line 117](https://git.key-project.org/key/key/-/blob/7514d7421a0c1aea52db55ae679708c0647e0289/key/key.util/src/main/java/org/key_project/util/collection/KeYCollections.java#L117) checks the A-Z condition twice it is likely that it was intendet to check for a-z one time instead.

Fixing that would lead to a wider varity of names used.
But it also breaks some tests that expect variables to have some fixed name and I don't have any idea if something depends on `KeYCollections::filterAlphabetic` only returning uppercase strings.

If it is decided to keep the current implementation, the dublicated condition in `KeYCollections::filterAlphabetic` should get removed, as well as its javadoc fixed and the javadoc of `MiscTools::filterAlphabetic`

(at)mulbrich you are in the javadoc as author

(at)weigl you commited that `KeYCollections` in 0f1932d3f9b (seems like it was extracted from `MiscUtils`)
    
----
    
Information: 
* created_at: 2021-12-13T11:12:28.928Z
* updated_at: 2021-12-13T11:44:29.973Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 1

**Comment by FliegendeWurst** [comment]
Fixed
