### ISSUE TITLE
Settings Dialog: Appearance -> Font Factor for Sequent and Proof Tree Requires Restart to Take Effect

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1648]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1648) where the discussions are preserved.
    
----
    
 

## Description

Using the settings dialog to change the font size of the sequent and proof tree, requires a restart of KeY to take effect.
This is independent of using "Apply" or "OK" button.

Changing the global factor takes effect immediately after clicking "Apply" or "OK"

Further the global factor is a factor, so named correctly.

The entry "Tree and sequent font factor" is actually a font size and should be renamed to "Tree and sequent font size" (btw. should we allow other font sizes as well?)

## Reproducible
  
always (macos 12.1)

### Steps to reproduce 

> Describe the steps needed to reproduce the issue.

0. Load a problem
1. Open the Options > Settings
2. Select "Appearance & Behaviour"
3. Change "Tree and sequent font factor" 
  -  Press "Apply" -> Nothing happens
  -  Press "OK" -> Nothing happens (Except as expected the dialog disappearing, but no font size changes in the sequent or proof tree)
4. Restart -> Font size has changed of sequent and tree

> What is your expected behavior and what was the actual behavior?

### Additional information

nothing more to add

---

* Commit: 57a19c0ce6fb08e9dcf183eb4116afbc72d85b05 

    
----
    
Information: 
* created_at: 2021-12-18T15:02:59.093Z
* updated_at: 2021-12-20T15:09:03.282Z
* closed_at: None  (closed_by: )
* milestone: v2.12.0
* user_notes_count: 2

**Comment by FliegendeWurst** [comment]
Fixed in #3216
