### ISSUE TITLE
Variable redeclaration error message

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1657]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1657) where the discussions are preserved.
    
----
    

## Description
Loading a file that redeclares a ghost variable or a normal variable returns a useless error message:
```
Recoder: 1 errors have occurred - aborting.
```
Url: \<parent folder\>
\<listing of the parent folder\>

## Reproducible

always

### Steps to reproduce 
Load this [file](/uploads/366006f2bdde97a51dfac2b22551adbb/Test.java).

### Additional information
* Commit: 666bcb0c95d451b4d1b2a2eaf683625bfbee210e
* Windows 10 Education Version 1909
    
----
    
Information: 
* created_at: 2022-01-02T18:41:59.148Z
* updated_at: 2022-01-04T04:29:32.199Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 1

**Comment by FliegendeWurst** [comment]
Error message in recent KeY is a lot better
