### ISSUE TITLE
Sum in model method is not replaced with bsum

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1687]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1687) where the discussions are preserved.
    
----
    
The sum in a model method is not replaced with bsum.

## Reproducible
Load the following file: [Buffers.java](/uploads/b001f384fc3ed140a7acc35fa324961f/Buffers.java)

All functions `test_{*}` fail to prove since there are no rules to apply and using the definition of `count` returns `sum`. `test_static` is unprovable because it needs `\typeof(this) == \type(Buffers)` to use the definition for some reason.

They are all not true in this current format because specifications were removed to reduce the test case. This is only about the `sum` appearing at which point no futher rules can be applied.

### Additional information
* Commit: 9d0bb84120f4ed6df569d0196b0c688fd2c488ab
    
----
    
Information: 
* created_at: 2022-02-03T13:48:23.528Z
* updated_at: 2022-02-03T22:50:03.017Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 7

**Comment by mattulbrich** [comment]
To summarise the discussion on gitlab: In the example, `a <= 0 < b` was used instead of `0 <= a < b`. Hence, the sum term was not translated as expected.

However, there should be a new issue discussing how to deal with more general sum terms.
