### ISSUE TITLE
Tasks for the Disclosure of KeY

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1728]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1728) where the discussions are preserved.
    
----
    
For details please refer to the Wiki page [Migration2022](https://git.key-project.org/key/key/-/wikis/Migration2022)

We are currently in the preparation phase.
    
----
    
Information: 
* created_at: 2022-11-30T20:15:54.900Z
* updated_at: 2022-12-06T17:06:34.601Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
I think these are all done.
