### ISSUE TITLE
DRAFT: Null Treatment in Type Hierarchy

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1737]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1737) where the discussions are preserved.
    
----
    
When applying method contracts, invariants etc., KeY uses the type hierarchy to figure out the applicability.

Now the problem: For the `null`, class invariants and method contracts for all classes are applicable. Since the `Null` type in KeY's type hierarchy inherits from all Java class types. See Fig. 2.3 on p. 28 in the KeY book.

Soundness is no longer a problem. We needed an extra `self != null` check for class invariants (see !513) and method contracts (with the `Null Reference` goal).

## Suggestion

Split all Java class types into a version with `null` and a version without `null`. Then the type hierarchy looks like this:

![type_hierarchy_mod](https://user-images.githubusercontent.com/74923113/215792782-7757fce6-2fd6-4ea0-9baa-f52d674cd673.svg)

For example, for a class `B` we would have a type `B` and `B+Null`, where `B` is subtype of `B+Null` and `Object`, and where `B+Null` is subtype of `Object+Null`. Note that the `Object` no longer includes `null` here.

Now we can design our class invariants and method contracts, such that they are only applicable to Java class types without `null`. We do no longer need explicitly handle the `null` case in method contracts and class invariants.

There should also be some additional changes in the calculus necessary: For example, assignements, `@nullable` or `@non-null` treatment.

## Additional Info

(at)rbubel noticed that after the fix !513, KeY's proof search might take longer. I have never forgot that and eventually it came to me that we could perhaps do better if the type hierarchy was designed differently.

The other problem was that for a large JavaRedux, KeY takes serveral minutes to load. I already talked about it with (at)fbauer who is currently writing his master thesis on improving JavaRedux. You might think, we can optimize the loading, but there is a problem: Since any method contract or any class invariant could be theoretically applicable to any null object, we need to load any class...
    
----
    
Information: 
* created_at: 2023-01-18T12:52:41.061Z
* updated_at: 2023-01-18T12:52:41.061Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by lks9** [comment]
Now this is #3019.
