### ISSUE TITLE
Can not use loop variable to set an ghost array

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#178]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/178) where the discussions are preserved.
    
----
    
* Mantis: [MT-1399](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1399)
* Submitted on: 2014-01-15 by (at)greiner
* Updated: 2014-01-21

### Description

> If you use a loop variable to update an entry of an ghost array within a loop, the expression can not be parsed.
> 
> If you use a constants instead, it works fine.

### Steps to reproduce

```
Load file attached
```

## Files

  
`GhostLoop.java`:

```java

public class GhostLoop {

	/*@ public ghost int[] arrs; */
	
	/*@ public normal_behaviour
	  @ ensures true;
	 */
	public int foo() {
		//@ set arrs = new int[4];
		int x = 3;
		for (int i = 0; i < 4; i++) {
			x++;
			//@ set arrs[i] = x;
		}
		return x;
	}
	
}

```

## History

* (at)greiner -- (`NEW_BUG`) _2014-01-15_

* (at)greiner -- (`FILE_ADDED`) _2014-01-15_

* (at)ruch -- (`NORMAL_TYPE`) _2014-01-21_

## Attributes

* Category: JML Parser
* Status: NEW
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: ALWAYS
* Platform: 
* Commit: dbc5885afe107ee58d1cd7ddbe282184fe345934
* Build: 
* Tags []
* Labels:  ~JML Parser  ~Bug  ~NORMAL  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1399)
    
----
    
Information: 
* created_at: 2017-05-29T02:31:14.035Z
* updated_at: 2022-10-13T12:20:49.686Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
Fixed in recent KeY
