### ISSUE TITLE
replace_known rules are not proof confluent

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#249]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/249) where the discussions are preserved.
    
----
    
* Mantis: [MT-429](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=429)
* Submitted on: 2004-10-14 by (at)rbubel
* Updated: 2005-03-11

### Description

> The "replace_known" rules are not proof confluent as in
>   p ==> p
> one can apply replace_known on the p in the antecedent and gets
>   true ==> p
> One may have to add an addrule storing the fact "p" e.g. 
> as 
>   ...
>   addrule { known_fact { add (p ==>); } }

## Notes

_(at)pruemmer at 2004-10-19_
> The same holds for the rules "apply_eq" for applying equations, which can be used to rewrite an equation referring to itself, and for the taclets "all_left_delete" and "ex_right_delete". Concerning "replace_known_*" and "apply_eq", I think these phenomena have to be regarded as a restriction of the taclet language as it is implemented in KeY at the time, which does not allow to specify that find- and if-formulas have to be distinct. For the time being, it would only be possible to alter the taclets "replace_known_*" and "apply_eq" to introduce taclets for restoring the original formula in any situation (or to use the taclet statement "add" instead of "replacewith", which would probably lead to further performance issues.
> 
> The definition of the existing strategies ensures that no destructive rule applications are performed, but this is only working around the real problem.

_(at)rbubel at 2005-03-11_
> * all_left_delete/ex_rigth_delete replaced by all_left_hide and ex_right_hide
> 
> The other issues from above remain.

## History

* (at)rbubel -- (`NEW_BUG`) _2004-10-14_

* (at)pruemmer -- (`BUG_MONITOR`) _2004-10-19_

* (at)pruemmer -- (`BUGNOTE_ADDED`) _2004-10-19_

* (at)rbubel -- (`BUGNOTE_ADDED`) _2005-03-11_

## Attributes

* Category: Calculus
* Status: NEW
* Severity: MINOR
* OS: 2.4.x
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: ALWAYS
* Platform: x86
* Commit: None
* Build: 0.1299
* Tags []
* Labels:  ~Calculus  ~Bug  ~NORMAL  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=429)
    
----
    
Information: 
* created_at: 2017-05-29T02:33:02.085Z
* updated_at: 2017-05-29T02:33:02.295Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
This has been fixed, the rule cannot be instantiated using itself
