### ISSUE TITLE
Status bar not updated after automode finished

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#286]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/286) where the discussions are preserved.
    
----
    
* Mantis: [MT-1466](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1466)
* Submitted on: 2014-07-07 by (at)grahl
* Updated: 2014-11-05

### Description

> The status bar is not updated or seems to be stuck after the automode has finished. I can keep working normally, but the status line shows "Processing Strategy" and the progress bar shows some figure != 100%.
> 
> It seems to be introduced recently, with all the changes to SwingWorkers and listeners, but I cannot put my finger on it.

## History

* (at)grahl -- (`NEW_BUG`) _2014-07-07_

* (at)mulbrich -- (`TAG_ATTACHED`) _2014-07-07_

* (at)grahl -- (`NORMAL_TYPE`) _2014-10-06_

* (at)grahl -- (`NORMAL_TYPE`) _2014-11-05_

## Attributes

* Category: GUI
* Status: NEW
* Severity: TWEAK
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: LOW
* Reproducibility: SOMETIMES
* Platform: 
* Commit: cb75aaf5b69d21b530eef000eb195b7ecd9008c0
* Build: 
* Tags [{'name': 'swingworker'}]
* Labels:  ~GUI  ~LOW  
* Version: _2.2_ 

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1466)
    
----
    
Information: 
* created_at: 2017-05-29T02:33:58.904Z
* updated_at: 2017-05-29T02:33:59.205Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
Fixed
