### ISSUE TITLE
Line numbers are corrupted when font size is increased

### ISSUE THREAD

**Issue by mattulbrich** [KeYProject/key#3123]
## Description

Inceasing the font size destroys the line number layout on the source code pane.

## Reproducible
  
always

### Steps to reproduce 

Load a file with sources. Increase font size to maximum

### Additional information
![image](https://user-images.githubusercontent.com/17046629/233048873-6ff6af10-5a35-4bf9-a41b-d4657da89687.png)

---

* Commit: 5ecc1aa79407e18e215e6c20e075748673b28a98

**Comment by FliegendeWurst** [comment]
After restarting KeY, the issue disappears.
