### ISSUE TITLE
KeY parsing pretty-printed terms can change operator precedence of `/` and `%`

### ISSUE THREAD

**Issue by ChristianHein** [KeYProject/key#3130]
## Description

I have a term of the form `a / b % c` in my sequent (with pretty syntax on). Here, the division takes precedence over modulo (and is thus equivalent to `(a / b) % c`). The issue: If I use this term in the taclet instantiation window (e.g. cut rule) then the term gets parsed differently as `a / (b % c)`. This unexpectedly changes the operator precedence.

It's easy to accidentally cause this if part of your workflow is to click-drag or copy-paste terms from the sequent into the cut rule window, for example.

## Reproducible

Always.

### Steps to reproduce 

1. Load a problem like below:
```
\problem {
    (10 / 5) % 2 = 0
}
```
(Notice the parentheses around the division. If you omitted them the term would display as `10 / (5 % 2) = 0` in the sequent.)

2. Make sure pretty syntax is on. You should see ` ⟹ 10 / 5 % 2 = 0`.
3. Check that the division is taking precedence over the modulo (hover your mouse over the subterms).
4. Apply the cut rule and enter the same fomula `10 / 5 % 2 = 0`.

**Expected behavior:**  
The new formula on the sequent is also `10 / 5 % 2 = 0` (or, alternatively, `(10 / 5) % 2 = 0`).

**Actual behavior:**  
The new formula on the sequent is `10 / (5 % 2) = 0`.

### Additional information

Here's how variations of the above term are parsed in KeY:

`10 / 5 % 2` → `10 / (5 % 2)`  
`(10 / 5) % 2` → `10 / 5 % 2`  
`10 / (5 % 2)` → `10 / (5 % 2)`  

`10 % 5 / 2` → `10 % (5 / 2)`  
`(10 % 5) / 2` → `10 % 5 / 2`  
`10 % (5 / 2)` → `10 % (5 / 2)`  

Related: #1560 #1192 #726 

---

* Commit: 5ecc1aa794

**Comment by mattulbrich** [comment]
I think it also involves multiplication:
* Input `2*3/6` is pretty printed as `2 * (3 / 6)`
* Input `(2*3)/6` is pretty printed as `2 * 3 / 6`

Primarly responsible are these lines in the parser:
https://github.com/KeYProject/key/blob/203d4bc985e2079c6d39e7be9351d2eebe594dae/key.core/src/main/antlr4/KeYParser.g4#L349-L350

These things are strange:
* `/` is right associative which is counter-intuitive
* `*` binds less than `/` which is also not what you would expect.

My take would be: Let us adapt the parser to what the pretty printer actually does right. Should be easy.
/cc @wadoon

**Comment by mattulbrich** [comment]
I actually do not think so. Division is right-assoc due to the grammar. Mul and Div should not be in different precedence levels like they are. Don't think that the magic really happens there. ...

**Comment by wadoon** [comment]
> I actually do not think so. Division is right-assoc due to the grammar. Mul and Div should not be in different precedence levels like they are. Don't think that the magic really happens there. ...

There is the magic. The grammar says, a sequence of terms separated by `/` or '%' is a strong_arith_term. This methods build the sequence into the binary term structure. 

The difference between left/right assoc is now foldLeft or foldeRight in Haskell terms.
