### ISSUE TITLE
Inconsistency of Proof Tree Settings Upon Loading a Proof

### ISSUE THREAD

**Issue by mi-ki** [KeYProject/key#3151]
## Description

The proof tree settings that are displayed in the menu sometimes do not reflect the actual proof tree settings shown in the displayed proof tree. It seems that this occurs "only" upon loading a proof, until the specific settings option is first changed.

For example, when loading a proof, the option "Hide Intermediate Proofsteps" is ticked, even though it is not active. Unchecking the option the first time (correctly) results in (still) showing intermediate proof steps, then checking the option (again) results in hiding intermediate proof steps.

The observed settings inconsistency seems to occur upon each proof loading in the GUI, have not tried it for proof selection via the command line.

## Reproducible
  
Always.

### Steps to reproduce 

1. Start KeY.
2. Select "Sum and Max" from the examples dialogue.
3. Select "JML normal_behavior operation contract 0" and start proof.
4. Apply the "impRight" rule to the outermost implication.
5. Observe the proof tree and the checkmarks from its settings menu.

### Expected behavior
Hidden intermediate proof steps, as indicated by the checkmark in the proof-tree settings menu.

### Actual behavior
Unhidden intermediate proof steps, even though the checkmark indicated otherwise.
See also the attached screenshots.

### Additional information

**Checkmarks upon loading the proof:**
![Checkmarks upon loading the proof](https://github.com/KeYProject/key/assets/6670500/8a4b55e2-e3a8-4666-ad18-c4da800f080e)

**Selection of some proof rule:**
![Selection of some proof rule](https://github.com/KeYProject/key/assets/6670500/67476791-7af7-4e02-ac52-bcb850225091)

**The resulting proof tree is inconsistent:**
![Resulting proof tree is inconsistent](https://github.com/KeYProject/key/assets/6670500/e9d82f06-6634-4fad-8163-4570b447c611)

**See also the wrong checkmark:**
![See also the wrong checkmark](https://github.com/KeYProject/key/assets/6670500/4c8759c5-36f6-4834-8ad5-170971213eec)

---

* Commit: 58af713f232a9377f0eb5998d60ffcb65dfbf6f7 (current main branch)

**Comment by jwiesler** [comment]
Help wanted: Can't reproduce. For me no filter is selected and everything works as expected.

**Comment by jwiesler** [comment]
The dropdown actually reflects the state of the filters. Somehow, the proof tree does not apply them correctly.

**Comment by jwiesler** [comment]
I've narrowed it down to the changes to these lines: https://github.com/KeYProject/key/blob/main/key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreeView.java#L433

@FliegendeWurst could you take a look please?

**Comment by FliegendeWurst** [comment]
See #3154 for a fix.

**Comment by jwiesler** [comment]
@FliegendeWurst great thanks!
