### ISSUE TITLE
keyext.slicing: 

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#3176]
## Description

Artiweb does not work anymore, because of a huge JUnit report:

```
File pull-requests/3141/754371258/keyext.slicing/build/test-results/test/TEST- 
org.key_project.slicing.EndToEndTests.xml is 220.67 MB; this exceeds GitHub's file size limit of 100.00 MB        
```

Also `TEST-de.uka.ilkd.key.parser.TestParser.xml` is huge (50 MB) but not rejected.

> Please describe your concern in detail!

Please shrink down the output of your test cases to a reasonably size!

**Comment by FliegendeWurst** [comment]
There is a fix in #3177
