### ISSUE TITLE
Glitches to be fixed for 2.12

### ISSUE THREAD

**Issue by mattulbrich** [KeYProject/key#3214]
## Description

Issues identified during UI testing for the release 2.12.

Please add your points below:
* [x] Increasing the font size affects the proof tree only after a restart of KeY. But the distances are decreased. (s. A)
* [x] The Proof Statistics Window looks strange with the chaged font sizes. (s B)
* [x] What does "Copy referenced proof" mean. There should be a tooltip.
* [x] When removing the .key directory, recent files are no longer stored (s. C)

### Images:
A: 
![image](https://github.com/KeYProject/key/assets/17046629/6f63593e-99bb-4629-8530-8e095c2ccfed)

B:
![image](https://github.com/KeYProject/key/assets/17046629/651810d7-f3e3-4c9a-bc1b-b663ff49bf51)
![image](https://github.com/KeYProject/key/assets/17046629/92176f07-04b1-45a1-a875-a9f29daaea8f)

C:
```
Could not write recent files listjava.io.FileNotFoundException: /home/mattias/.key/recentFiles.props (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at de.uka.ilkd.key.gui.RecentFileMenu.store(RecentFileMenu.java:247)
	at de.uka.ilkd.key.gui.RecentFileMenu.save(RecentFileMenu.java:260)
```

**Comment by FliegendeWurst** [comment]
I fixed issue 4, but I can't reproduce the broken layout of the proof tree. Which font setting did you change?

**Comment by WolframPfeifer** [comment]
The statistics dialog (B) is better now as it has less superfluous space, but the button font does not match the rest of the text:
![image](https://github.com/KeYProject/key/assets/94171076/5064adb0-3d07-4edf-b340-de863d2d5dcd)

I think this is a general problem: Why do we have different font settings (for sequent/proof tree, and the rest)? Can we streamline this and have only a single global font factor setting?

And, by the way, I think that decreasing the font factor does not really work at the moment, as it affects only some places, but not in others, for example not in the tabs (proof tree, goals, etc.) and also not for the settings dialog itself. Increasing, on the other hand, has an immediate effect on all of them. This can lead to very strange situations, e.g. in this example after increasing to 1.5 and decreasing to 0.5 afterwards:
![image](https://github.com/KeYProject/key/assets/94171076/06b1e3e1-c164-453c-99c9-eace579357b3)
