### ISSUE TITLE
Loading a PO from the project manager makes KeY freeze

### ISSUE THREAD

**Issue by mattulbrich** [KeYProject/key#3215]
## Description

Loading a PO from the project manager makes KeY freeze.

## Reproducible
  
always on my machine

### Steps to reproduce 

1. Open the example selector window
2. Select "Remove Duplicates"
3. Select the first method PO
4. Run auto to close
5. Open the proof manager
6. Select the second method PO
7. KeY freezes

### Additional information

git bisect reveals that c07a00fba07e8513966c2e958d797a5d6023d424 is the culprit.

I wonder if this removal has to do with the problem:
```diff
     @Override
     public void progressStopped(Object sender) {
-        mainWindow.getMediator().startInterface(true);
+        // no need to call startInterface(), will be done by ProblemLoader once loading is done
     }
```

---

* Commit: 0ac6d7f2f89621db5bcd223c76470fdcc857ac4d

**Comment by FliegendeWurst** [comment]
You found the right change. I have a fix ready and will open a PR soon. By the way, step 4 is not needed.
