### ISSUE TITLE
Publications page on key-project.org links to empty bibtex file

### ISSUE THREAD

**Issue by FliegendeWurst** [KeYProject/key#3266]
## Description

The link to the [BibTeX file with all entries](https://www.key-project.org/?feed=tp_pub_bibtex&use_bibtool=1) on https://www.key-project.org/publications/ leads to an empty file.

cc @wadoon

**Comment by wadoon** [comment]
Where is this link? Readme? key-docs? wordpress?

**Comment by FliegendeWurst** [comment]
It is on https://www.key-project.org/publications/:

![image](https://github.com/KeYProject/key/assets/12560461/2b55279d-2f1f-4906-91c4-6af3080feaaf)

**Comment by wadoon** [comment]
Repaired by removing bibtool parameter. 

@unp1 There seems to something broken with bibtool on the system.
