### ISSUE TITLE
JML Assert Statement Mutable During Proving

### ISSUE THREAD

**Issue by unp1** [KeYProject/key#3300]
## Description

The JML Assert Statement is mutated during a proof when a rule using the IntroAtPre term transform is used via method updateVars. 

This changes existing terms in the sequent.

## Reproducible
  
always

### Additional information

Terms and AST nodes must be immutable. Breaking this means that the terms and previous nodes are changed as well.
 

---

* Commit:

**Comment by wadoon** [comment]
solved by #3400
