### ISSUE TITLE
[2.12.1] Solver file Z3_QF.props could not be loaded.

### ISSUE THREAD

**Issue by FliegendeWurst** [KeYProject/key#3323]
## Description

When running the 2.12.1 release jar, the warning `Solver file Z3_QF.props could not be loaded.` always shows up on launch.

## Reproducible
  
always

### Steps to reproduce 

1. Download and run key-2.12.1-exe.jar

Expected: no warning

### Additional information

The warning occurs because Z3_QF is mentioned in `solvers.txt` but not included in the jar. This kind of issue is fixed by #3287, but that PR never made it to the 2.12.1 branch.

**Comment by WolframPfeifer** [comment]
This issue is resolved on main and in the bugfix release 2.12.2.
