### ISSUE TITLE
Assignable prevents proving the algorithm

### ISSUE THREAD

**Issue by fab918** [KeYProject/key#3362]
## Description

When I use "assignable" in the Key Editor, I have my proof which fails, yet the method does not modify anything. If assignable is removed, it works. This doesn't seem to limit to "\nothing", if I put array or array[*] it still doesn't work.

(I take advantage of this, is it possible to have more information on what is not working? I did not find any information on this subject, it is not clear where the problem lies)

## Reproducible
  
yes

### Steps to reproduce 

```java
public class Test {
    /*@ requires array != null && array.length > 0;
      @ ensures \result == (\sum int i; 0 <= i && i < array.length; array[i]);
      @ assignable \nothing;
      @*/
    public static int sum(int[] array) {
        int total = 0;
        
        //@ maintaining 0 <= i && i <= array.length;
        //@ maintaining total == (\sum int j; 0 <= j && j < i; array[j]);
        //@ decreases array.length - i;
        for (int i = 0; i < array.length; i++) {
            total += array[i];
        }
        return total;
    }
}
```

> What is your expected behavior and what was the actual behavior?

pass the test

**Comment by mattulbrich** [comment]
Hi fab918, thanks for the report.

Try adding `//@ assignable \nothing;` to the loop specification (like above `decrease`).
That should help.

**Comment by mi-ki** [comment]
I had implemented such an alias some years ago, but apparently this did not survive the release cycles. Shouldn't be a problem to reintroduce it though, in my opinion.

**Comment by fab918** [comment]
@mi-ki Is there any trace of your contribution? I did a search on PRs but I don't see it.

**Comment by mi-ki** [comment]
@fab918 I just took a look, but found out I did not introduce an alias for `loop_modifies` or `loop_writes`, but for `loop_variant` and `assigns` (yet another standard from somewhere else, apparently). This was commit af97f72d1994cb50c74eb04c77649f198236f8ec. However, I am not sure whether their translation still works as it used to do, since many hard-to-follow things happened to the parser in-between.

**Comment by fab918** [comment]
@mi-ki Thanks, unfortunately I don't think it always works.

 If anyone has any advice on how to get started, I'd love to hear it.

**Comment by mi-ki** [comment]
@fab918 I created a new branch which should hopefully fix the previously lost changes and also add the two keywords from OpenJML. Maybe, you can test whether it works for you?

**Comment by mi-ki** [comment]
It's been a while and after various internal discussions, the PR #3365 made it onto the main branch.
So, @fab918, if you are still around, feel free to use it!
