### ISSUE TITLE
Proof independent settings seem to be no longer saved

### ISSUE THREAD

**Issue by unp1** [KeYProject/key#3366]
## Description

> Please describe your concern in detail!

Deactivating an extension (like Javac, Caching) does not work.

## Reproducible
  
> Is the issue reproducible?
> Select one of: always, sometimes, random, have not tried, n/a 

always

### Steps to reproduce 

> Describe the steps needed to reproduce the issue.

1. Delete (move) ~/.key
2. Start KeY
3. Deactivate, for instance the JavaC extension
4. Quit KeY 
5. Restart KeY
6. Deactivated extension is activated

> What is your expected behavior and what was the actual behavior?

Extension is deactivated

---

* Commit: 7a43f16166e229144bab3c5688a8e89ac4d35026

**Comment by Drodt** [comment]
It seems that settings in general are not saved. Changing the appearance or font size also gets lost.

**Comment by FliegendeWurst** [comment]
I fixed the particular case of not being able to disable extensions in #3392

**Comment by FliegendeWurst** [comment]
This is fixed now that #3392 is merged
