### ISSUE TITLE
Proof tree filters not applied correctly

### ISSUE THREAD

**Issue by WolframPfeifer** [KeYProject/key#3367]
## Description
The filters in the proof tree ("Hide Intermediate Proofsteps" etc.) are not applied correctly, at least in the case of a freshly started proof.

## Reproducible
always

### Steps to reproduce 

1. Start any proof and apply some rules or macros to it.
2. Select "Hide Intermediate Proofsteps" in the proof tree settings (gear wheel).

I would expect that the intermediate proof steps are filtered out. However, the proof tree stays as it is (no filters applied). 
Furthermore, if the menu is opened again, the checkbox is not ticked.

### Additional information

* By bisecting, I found the first bad commit: 3ab8750d0e35f3a5d694d4c0e8bf196a7f1b2607.
* The problem seems to have something to do with the focus: At least in my testing, it only happened in freshly started proofs. If multiple proofs are present, after switching between them, the filters work fine.

**Comment by WolframPfeifer** [comment]
@unp1 The commit that introduced this problem is 3ab8750d0e35f3a5d694d4c0e8bf196a7f1b2607. It seems that you tried to do some refactoring here ...

**Comment by mi-ki** [comment]
> @mi-ki I think this is the issue you mentioned to me yesterday, right?

@WolframPfeifer Yes, you are right, thanks for looking into it!
