### ISSUE TITLE
KeY crashes after initial launch terminates unconventionally

### ISSUE THREAD

**Issue by BookWood7th** [KeYProject/key#3416]
## Description

> When KeY is launched without an existing .key directory, it creates this directory. Upon termination of the program KeY would write its settings in that directory. If KeY is not terminated through its provided methods, the settings are not written to a file.
When next launching KeY it finds the directory, but cannot load the settings. Thus it fails to start and crashes.

## Reproducible
  
> Is the issue reproducible?
always

### Steps to reproduce 

> Describe the steps needed to reproduce the issue.

1. Ensure there is no .key directory
2. Launch KeY
3. Kill the process
4. Launch KeY again

> What is your expected behavior and what was the actual behavior?

expected: KeY launches and loads standard settings
actual: KeY fails to launch

### Additional information

Caused by: java.lang.NullPointerException: Cannot invoke "de.uka.ilkd.key.settings.Settings.addPropertyChangeListener(java.beans.PropertyChangeListener)" because "settings" is null

---

* Commit: 5b08998f3cc0c0236fbe30abaf51901871d76dbe

**Comment by BookWood7th** [comment]
PS: Issue is still present in 1fb0c10630b493ce138850ae0f9803d3f2fffc51

**Comment by FliegendeWurst** [comment]
I couldn't reproduce the issue.

**Comment by FliegendeWurst** [comment]
I was finally able to reproduce the issue by removing ~/.key/colors.json
