### ISSUE TITLE
Control-C may leave a defunct process

### ISSUE THREAD

**Issue by mattulbrich** [KeYProject/key#3456]
## Description

When starting KeY from the command line, pressing ctrl-c prior to the main window's appearance leaves KeY in a defunct state that can only be killed from outside. Pressing ctrl-c again does not help.

## Reproducible

sometimes.

It seems the time when ctrl-c is pressed plays a role. It seems  that KeY must be in a state where the signal is registered, yet the exit action does not have its full effect yet.

### Steps to reproduce 

Start KeY from the command line (e.g. using the shadow jar) and press ctrl-c before the window shows up.

It should terminate, but instead it only prints `WARN  WindowUserInterfaceControl - Caught SIGINT, exiting...`to the console and gets stuck.

### Additional information

The signal handler seems to have been introduced in 2ff6a372056.

---

* Commit: 9cc569ccced37e242b3a85779f2afdc42b0031ca

**Comment by mattulbrich** [comment]
Nice issue number btw :smile:

**Comment by wadoon** [comment]
In #3451, I have already removed this part. This class is part of the module `jdk.unsupported`. I think the authors want to tell us something with this name. 🤔

**Comment by WolframPfeifer** [comment]
Closed by #3499.
