### ISSUE TITLE
KeY GUI slows down already at proofs of size 10000

### ISSUE THREAD

**Issue by unp1** [KeYProject/key#3500]
## Description

The proof tree rendering slows down for medium sized proof trees.  

## Reproducible
  
always

### Steps to reproduce 

> What is your expected behavior and what was the actual behavior?

### Additional information

Problem is the tooltip rendering removing it resolves the problem, but we loose any nice proof tree label rendering, so a better solution is needed.

---

* Commit:

**Comment by mattulbrich** [comment]
It seems that the tooltips on the proof tree (I assume the problem is about them) cannot be switched off at all. Would be nice if there was a tick box in the local menu to get rid of them ...
@unp1
