### ISSUE TITLE
Location#compareTo(Location) breaks with undefined Location

### ISSUE THREAD

**Issue by BookWood7th** [KeYProject/key#3518]
## Description

The Location class may be instantiated without an associated file. This causes fileUri to be null. Due to this Location::compareTo causes a NullPointerException, when used by a Location without an associated file

## Reproducible
 
always

### Steps to reproduce 

> Describe the steps needed to reproduce the issue.

1. Create a Location without an associated fileUri (Location.UNDEFINED / any constructor values with fileUri set to null)
2. Create a second Location object
3. call compareTo on the first Location comparing it to the second

Expected to sort by their Position objects. Actually throws NullPointerException.

### Additional information

---

* Commit: 
[8e28439](https://github.com/KeYProject/key/commit/8e284394d2e0d70dc54fe684ec9c707b6f60a7df)

**Comment by BookWood7th** [comment]
The issue actually does not concern Location but instead IssueDialog where sorting is done without checking for these NullPointerExceptions

**Comment by mattulbrich** [comment]
Well, `compareTo` should not fail for valid argument objects, so I'd say it is a bug in the comparison.

Probably easy to fix by making the comparison `null`-aware, isn't it?

**Comment by BookWood7th** [comment]
The issue is reasonably easy to fix and I believe I found a somewhat elegant solution to this.
The proposed solution adds explicit nullsLast comparators that check for null values of fileUri and position fields in Location before using the respective natural order of these fields.

**Comment by BookWood7th** [comment]
Was fixed in #3519
