### ISSUE TITLE
Proofs using taclet introduction (e.g., weakening rules) cannot be loaded

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#37]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/37) where the discussions are preserved.
    
----
    
* Mantis: [MT-1543](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1543)
* Submitted on: 2015-05-17 by (at)klebanov
* Updated: 2015-06-10

### Description

> If a taclet is introduced by another taclet during a proof (e.g., hide_left), the introduced taclet is named based on a global counter. The name is thus influenced by pruning the proof, order of rule application on different branches, etc. The name is not saved with the proof at the moment of introduction, thus later during loading the introduced taclet may not be available under the same name. It is a matter of pure luck that proofs using weakening (any serious proof) can be loaded at all.
> 
> A solution would be to save the introduced name with the proof and use it when the taclet is to be introduced in the proof instance that is being loaded.

## Notes

_(at)grahl at 2015-06-10_
> is this in the 2.4.1 release,too?

## History

* (at)klebanov -- (`NEW_BUG`) _2015-05-17_

* (at)grahl -- (`BUGNOTE_ADDED`) _2015-06-10_

## Attributes

* Category: Proof Loading/Saving
* Status: NEW
* Severity: MAJOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: HIGH
* Reproducibility: SOMETIMES
* Platform: 
* Commit: c2f138489e0860de48c0887885f03b7bbe448b6e
* Build: 
* Tags []
* Labels:  ~Proof Loading/Saving  ~Bug  ~HIGH  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1543)
    
----
    
Information: 
* created_at: 2017-05-29T02:26:59.780Z
* updated_at: 2021-10-15T13:04:50.996Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
Taclet naming is now based on the location of the node in the proof tree
