### ISSUE TITLE
add nice-to-write syntactic sugar for sequence construction

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#395]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/395) where the discussions are preserved.
    
----
    
* Mantis: [MT-1130](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1130)
* Submitted on: 2011-11-09 by (at)grahl
* Updated: 2011-11-09

### Description

> I would pref writing a sequence as something like \seq{1,3,3,2} instead of \seq_concat(\seq_singleton(1),\seq_concat(\seq_singleton(3),\seq_concat(\seq_singleton(3),\seq_concat(\seq_singleton(2)))))

## History

* (at)grahl -- (`NEW_BUG`) _2011-11-09_

* (at)grahl -- (`NORMAL_TYPE`) _2014-01-03_

## Attributes

* Category: JML (semantics)
* Status: NEW
* Severity: FEATURE
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: LOW
* Reproducibility: NOTAPPLICABLE
* Platform: 
* Commit: None
* Build: 
* Tags []
* Labels:  ~JML (Semantics)  ~Feature  ~LOW  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1130)
    
----
    
Information: 
* created_at: 2017-05-29T02:36:32.071Z
* updated_at: 2017-05-29T02:36:32.071Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by mattulbrich** [comment]
As of 4d03fc8eb5952abf1bfc509d97e578ba, a syntax similar to the above is available on the main branch. You can write `\seq(1,2,3)`.

**Comment by mattulbrich** [comment]
On the JML level you can now write `\seq(1) + \seq(2,3)` for concatenation.

**Comment by mattulbrich** [comment]
Closed after discussion with Daniel @Drodt and Richard @unp1
