### ISSUE TITLE
No symbolic execution rule available to treat += reading a static array index.

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#482]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/482) where the discussions are preserved.
    
----
    
* Mantis: [MT-1574](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1574)
* Submitted on: 2015-09-23 by (at)mhentschel
* Updated: 2015-09-23

* Assigned to: (at)rbubel

### Description

> No rule available to treat += reading a static array index.

### Steps to reproduce

```
Start a proof of the attached example and try to finish the attached example. No rule is applicable to treat the statement:
sum += arr[n];
```

## Files

  
[Bug.java](/uploads/b5556984010ddf89f7d1916fb41c657f/Bug.java)
  

## History

* (at)mhentschel -- (`NEW_BUG`) _2015-09-23_

* (at)mhentschel -- (`NORMAL_TYPE`) _2015-09-23_

* (at)mhentschel -- (`NORMAL_TYPE`) _2015-09-23_

* (at)mhentschel -- (`FILE_ADDED`) _2015-09-23_

## Attributes

* Category: Calculus
* Status: ASSIGNED
* Severity: MINOR
* OS: 
* Target Version: 2.6
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: HAVENOTTRIED
* Platform: 
* Commit: eff963a736c991e023578259348f159cd5643230
* Build: 
* Tags []
* Labels:  ~Calculus  ~Bug  ~NORMAL  
* Version: _2.6_ 

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1574)
    
----
    
Information: 
* created_at: 2017-05-29T02:38:27.284Z
* updated_at: 2017-05-29T02:38:27.580Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
Fixed in recent KeY versions.
