### ISSUE TITLE
Taclets all_left_int, all_left_hide_int are applicable when they should not be

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#583]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/583) where the discussions are preserved.
    
----
    
* Mantis: [MT-708](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=708)
* Submitted on: 2006-07-21 by (at)pruemmer
* Updated: 2006-08-11

### Description

> I assume that the taclets mentioned above have been introduced to hide problems/inconveniences with the new hierarchy of integers types. Something seems to go wrong with the matching of generic types, however, because the taclets are also applicable for quantifiers over types other than integer. This can be seen when looking at the file "quantifiers.key", where all terms are of the uninterpreted type "s" that has no relation to integers.

## Notes

_(at)rbubel at 2006-08-11_
> rewritten the rules. Thus only fixed symptoms and not the bug itself (combination of extends and oneOF of generic sorts does not work)

## History

* (at)pruemmer -- (`NEW_BUG`) _2006-07-21_

* (at)rbubel -- (`BUGNOTE_ADDED`) _2006-08-11_

## Attributes

* Category: Prover Core
* Status: NEW
* Severity: FEATURE
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: ALWAYS
* Platform: 
* Commit: None
* Build: 0.2256
* Tags []
* Labels:  ~Prover Core  ~Feature  ~NORMAL  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=708)
    
----
    
Information: 
* created_at: 2017-05-29T02:41:09.684Z
* updated_at: 2017-05-29T02:41:09.926Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
Fixed long ago (the mentioned taclets are gone)
