### ISSUE TITLE
progress bar unused during loading

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#687]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/687) where the discussions are preserved.
    
----
    
* Mantis: [MT-1390](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1390)
* Submitted on: 2013-12-13 by (at)grahl
* Updated: 2014-11-05

### Description

> Since the recent parser update, the progress bar doesn't display anythzing during loading.

## Notes

_(at)grahl at 2014-10-31_
> now (8c7345bac74b2a019711c352f176cc5d59259949) it has completely disappeared

## History

* (at)grahl -- (`NEW_BUG`) _2013-12-13_

* (at)ruch -- (`BUG_MONITOR`) _2014-01-22_

* (at)grahl -- (`NORMAL_TYPE`) _2014-10-06_

* (at)grahl -- (`NORMAL_TYPE`) _2014-10-06_

* (at)grahl -- (`BUGNOTE_ADDED`) _2014-10-31_

* (at)grahl -- (`NORMAL_TYPE`) _2014-11-05_

## Attributes

* Category: GUI
* Status: NEW
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: LOW
* Reproducibility: ALWAYS
* Platform: 
* Commit: e5edaf521023cf82fbc35adf641da6741d99e3ed
* Build: 
* Tags []
* Labels:  ~GUI  ~Bug  ~LOW  
* Version: _2.2_ 

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1390)
    
----
    
Information: 
* created_at: 2017-05-29T02:43:51.003Z
* updated_at: 2022-07-06T19:30:35.457Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
This was fixed recently.
