### ISSUE TITLE
Simplify complains: Bad input: Probable matching loop

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#710]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/710) where the discussions are preserved.
    
----
    
* Mantis: [MT-980](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=980)
* Submitted on: 2010-04-28 by (at)klebanov
* Updated: 2012-08-13

### Description

> I don't know if this is harmless/planned or a bug in the translation. See steps to reproduce.

### Steps to reproduce

```
-Try to verify Client::payday() from the example attached in #979
-Do an impRight
-run Simplify
-Do a couple of andLefts
-run Simplify
-decomposing the antecedent completely makes the problem go away surprisingly
```

## History

* (at)klebanov -- (`NEW_BUG`) _2010-04-28_

* (at)niederma -- (`NORMAL_TYPE`) _2010-04-29_

* (at)niederma -- (`NORMAL_TYPE`) _2010-04-29_

* (at)grahl -- (`NORMAL_TYPE`) _2012-08-13_

* (at)grahl -- (`NORMAL_TYPE`) _2012-08-13_

## Attributes

* Category: SMT
* Status: NEW
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: ALWAYS
* Platform: 
* Commit: None
* Build: 1ed20f0687dbe16c3c6ec8ad0455989f
* Tags []
* Labels:  ~SMT  ~Bug  ~NORMAL  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=980)
    
----
    
Information: 
* created_at: 2017-05-29T02:44:24.103Z
* updated_at: 2017-05-29T03:00:47.627Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
Fixed in recent KeY (no more Simplify). The provided files are proven automatically after fixing some missing bits.
