### ISSUE TITLE
Java pretty printing

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#765]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/765) where the discussions are preserved.
    
----
    
* Mantis: [MT-276](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=276)
* Submitted on: 2004-02-06 by (at)giese
* Updated: 2014-12-19

### Description

> Some poor student should be coerced into rewriting ...key.java.PrettyPrinter to use ...key.util.pp.Layouter
> 

## Associated Bugs

* Relates to MT-1518 with 

## History

* (at)giese -- (`NEW_BUG`) _2004-02-06_

* (at)grahl -- (`BUG_ADD_RELATIONSHIP`) _2014-12-19_

## Attributes

* Category: GUI
* Status: NEW
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: ALWAYS
* Platform: 
* Commit: None
* Build: 0.911
* Tags []
* Labels:  ~GUI  ~Bug  ~NORMAL  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=276)
    
----
    
Information: 
* created_at: 2017-05-29T02:46:42.069Z
* updated_at: 2017-05-29T02:46:42.069Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
Done in #3034

**Comment by jwiesler** [comment]
I guess I'm that poor student. :(
