### ISSUE TITLE
The counter example generation button is enabled if Z3 not installed, but does nothing

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#771]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/771) where the discussions are preserved.
    
----
    
* Mantis: [MT-1521](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1521)
* Submitted on: 2015-01-16 by (at)mulbrich
* Updated: 2015-01-16

* Assigned to: (at)herda

### Description

> 
> If you haven't Z3 installed (or it is not accessible ...), then pressing the CEG
> button has no effect.
> 
> The button should either be disabled (with a corresponding tooltip text) 
> or a message box should pop up and tell the user their fate.

## History

* (at)mulbrich -- (`NEW_BUG`) _2015-01-16_

* (at)mulbrich -- (`NORMAL_TYPE`) _2015-01-16_

* (at)mulbrich -- (`NORMAL_TYPE`) _2015-01-16_

## Attributes

* Category: Counter Example Generator
* Status: ASSIGNED
* Severity: TWEAK
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: ALWAYS
* Platform: 
* Commit: 5d1492b0f9e723203ef645f327602ea32ba8039a
* Build: 
* Tags []
* Labels:  ~Counter Example Generator  ~NORMAL  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1521)
    
----
    
Information: 
* created_at: 2017-05-29T02:46:52.398Z
* updated_at: 2017-05-29T02:46:54.072Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by WolframPfeifer** [comment]
Solved by merging #3239.
