### ISSUE TITLE
clean up parsers and update to ANTLR 4

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#789]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/789) where the discussions are preserved.
    
----
    
* Mantis: [MT-1165](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1165)
* Submitted on: 2012-02-03 by (at)grahl
* Updated: 2014-10-13

### Description

> The present parsers are messed up. Especially writing LL grammars for ANTLR v2 is tiresome (in comparison to LL* of ANTRLR v3).

## Files

  
[javacardapi.zip](/uploads/07090fdf5494f7d7f9b73d479e1411b1/javacardapi.zip)
  

## Notes

_(at)grahl at 2012-10-29_
> just found out that ANTLR v4 was released this month

_(at)grahl at 2013-12-06_
> keyparser and jmlpreparser (and their lexers) have been ported (thanks to Fabian).
> jmlparser is still on the agenda.

_(at)rbubel at 2013-12-06_
> First: Thanks to Fabian for taking that effort.
> 
> Second: A first issue report ;-) 
> I get a number of warnings like
> 
> As a result, alternative(s) 2 were disabled for that input
>      [java] Semantic predicates were present but were hidden by actions.
>      [java] warning(200): /Users/bubel/Documents/Development Projects/coreKeY/key/system/src/de/uka/ilkd/key/parser/KeYParser.g:2417:9: 
>      [java] Decision can match input such as "NOT_EQUALS" using multiple alternatives: 1, 2
> 
> 
> at the moment, which we should try to avoid in the mid-term.

_(at)rbubel at 2013-12-06_
> Fixed the warnings.

_(at)most at 2013-12-06_
> I am getting seriously worried. First of all, my Java Card transactions project does not load anymore into KeY, and by the looks of it, it is not a simple omission or fix. Even more worringly, all the things for model methods that I carefully worked on and have put on the master branch already also seem not to work anymore. I will wait for the master build to stabilise (BTW, since when did we start to treat the master branch as a trial-and-error branch that it now seems to be :/) and try to see what is going on. But I am not planning on spending two full weeks that I effectivelly have until the feature freeze to debug and reimplement what I have already done.

_(at)rbubel at 2013-12-07_
> Hi Wojciech, 
>  sorry about the problems. The master should be now stable again. The problem with the master was that the fixes seemed to be easy one-liners and obviously were not :-( 
> 
>    Could you please attach the JavaCard project to this bug so that we can look into it. Concerning the model methods, the JML parser itself has not yet been ported to ANTLR3, so I hope whatever broke, it should be repairable. Do you have for them also a small file which used to be parseable on the master and now stopped working?

_(at)most at 2013-12-07_
> There is one file on the master branch that "should" just load:
> 
> examples/heap/fm12_03_TreeDel/Tree.java
> 
> (though I cannot be 100% it was loadable on master before, but I am 90% sure). 
> W.r.t. parsers, the model methods mods dig deep into all JML parsers IIRC. The Java Card project will be now also attached.

_(at)most at 2013-12-09_
> OK, I did a little bit of digging in and this is really not looking good. In particular, the JML pre lexer is missing the whole thing (old ANTLR code) below. As you can see at this point it is really difficult for me to establish what else was wiped out in the process. And since I am not confident with ANTLR3 I am in no position to start putting those things back in. Currently checking in my model methods branch on master is pointless, which is a pity, because it is really ready (well, was on Thursday) and it does not involve the parser in any way. I am really lost to be honest.
> 
> BODY
> options {
>     paraphrase = "a method body";
> }
> {
>     int braceCounter = 0;
>     boolean ignoreAt = false;
> }
> :
>     {!expressionMode}?
>     '{'
>     (
>            '{'                      { braceCounter++; ignoreAt = false; }
>         |  {braceCounter > 0}? '}'  { braceCounter--; ignoreAt = false; }
>         |  '\n'                     { newline(); ignoreAt = true; }
>         |  ' '
>         |  '\u000C'
>         |  '\t'
>         |  '\r'
>         |  {!ignoreAt}? '(at)'
>         |  {ignoreAt}? '(at)'!         { ignoreAt = false; }
>         |  ~'}'                     { ignoreAt = false; }
>     )*
>     {braceCounter == 0}? '}'
> ;

_(at)most at 2013-12-09_
> I am very sorry, now I found the BODY definition in the new parser (no idea how I missed it). But the problem of my model methods not parsing remains. Will see if there is a quick fix for that.

_(at)rbubel at 2013-12-09_
> Hi, 
> 
>   I did also some digging and found a few more problems in the prelexer 
> 
> One problem is that LPARENT, RPARENT  were referenced in the parser sometimes with LPARENT sometimes with LPAREN. I change that locally to LPAREN. The next problem is that several symbols are matched by multiple tokens, e.g. '('  by LPAREN, JAVASEPARATOR, and other symbols
> 
> Fixing let's the parser continue further but I a hit at the moment a road block with this EOF matching tokens ...

_(at)most at 2013-12-09_
> In that case I wait patiently. The LPAREN(T) sounds like it may have something to do with my problem (actually both of them) too.

_(at)rbubel at 2013-12-10_
> Current state: The master branch does now load the Tree example of the FM competition again. The JavaCard project can not yet been parsed for at least the following reasons:
> 
> * The JML preparser adds to many spaces, such that 
>                  obj.<transient> becomes  obj.< transient >
>    and then the JML lexer  cannot recognise < transient > as implicit identifier.
> 
> * JML pre lexer cannot parse 0x<Something> which prevents hexadecimal numbers to be parsed later on

_(at)mulbrich at 2013-12-10_
> Hi,
> 
> cool that a first step towards a new parser is done. I am looking forward to more :-)
> 
> I have to report more trouble, however: There is no more error messaging
> with the new parser.
>    
> 
> private void semanticError(String message) throws RecognitionException {
>   throw new RecognitionException(input);
>   //throw new KeYSemanticException
>   //  (message, getSourceName(), getLine(), getColumn());
> }
> 
> Instead of a KeYsemanticException with position information, a mere
> RecognitionException is thrown.
> Can we not make the KeYSemanticException let extend RecognitionException?

_(at)mulbrich at 2013-12-10_
> I fixed that last mentioned issue about exceptions in commit
>    6694bd92bb6835af1ae1ccb9f93ebc5c3ef7fcdc  .
> 
> There seem to be (atleast) 2 different error reporting mechnisms (the KeY exc handler and throwing a RecognitionException) in the parser. Is there a reason for that?
> 
> Should we perhaps change everything to the KeYExceptionHandler?

_(at)rbubel at 2013-12-10_
> I agree that we should have just one error handling mechanism. I think the two are a remainder of an early (speak >10 years ago) effort of trying to improve the error handling ...

_(at)grahl at 2013-12-10_
> There should also be a way of reporting non-critical warnings.

_(at)most at 2013-12-11_
> Thanks Richard a lot for fixing things! My model methods branch could now be successfully merged and it seems to work again (minus the things that are still broken on the master). I will simply push the model methods changes (now it includes tests in runAllProofs), so we can avoid a situation like this in the future.
> 
> And indeed I did notice that the <...> notation in JML does not really work, also for .<inv> that still used to have here and there. 
> 
> On the plus side, I noticed that the KeY is way faster with reading in the files (but the progress bar does not seem to do much now).

_(at)grahl at 2013-12-11_
> The <...> is not supported in JML. And in my opinion, it's not worth implementing it.
> 
> The JML equivalent to o.<inv> is \invariant_for(o).
> 
> If you have other implicit attributes, I suggest to add dedicated keywords to JML like \transient(o).

_(at)grahl at 2014-10-13_
> Update: ANTLR 4 has been stable for two years now. We should update directly to ANTLR 4. The main points are support for left-recursion and Java 8 compilation. Adopting our grammars to the ANTLR 4 guidelines would make them much, much, much more readable and maintainable.

_(at)rbubel at 2014-10-13_
> Another advantage is that ANTLR 4 allows to import grammars into other grammars. Hence, we can have a grammar for FOL which is imported by the grammar for DL. Also it is possible to separate the grammars for key input files, taclets and DL in the same manner.

_(at)mulbrich at 2014-10-13_
> I believe the main force behind a parser refactoring should not be the version
> of the framework but the - very difficult task - of separating the syntactical
> parsing (AST) from the semantic analyses. That would improve maintainability
> tremendously. And that would be possible with all versions of the framework.
> What features of ANTLR4 would make this adaptation easier?

_(at)rbubel at 2014-10-13_
> To this extent ANTLR 4 provides besides tree grammars a nice listener framework that allow to implement semantic analysis conveniently. Basically the listener registers to a tree walker and is informed about events like entering or leaving a node.

_(at)mulbrich at 2014-10-13_
> Would you consider it possible to refactor the existing KeYParser into that form?
> We had already someone working on that and he could not disentangle the parser
> spaghetti code monster.
> 
> I would *love* to have a clean parser, but I would say switching to ANTLR4 w/o this
> major refactoring/rewriting should not be done.

_(at)rbubel at 2014-10-13_
> In general I would say yes that should be possible, but what were the concrete problems the student encountered? 
> 
> In any case, I agree without that kind of refactoring just moving to ANTLR 4 does not make sense

## Associated Bugs

* Relates to MT-1230 with 

* Relates to MT-767 with 

* Relates to MT-642 with 

* Relates to MT-1166 with 

## History

* (at)grahl -- (`NEW_BUG`) _2012-02-03_

* (at)grahl -- (`BUG_ADD_RELATIONSHIP`) _2012-02-03_

* (at)grahl -- (`NORMAL_TYPE`) _2012-02-08_

* (at)grahl -- (`BUG_ADD_RELATIONSHIP`) _2012-02-08_

* (at)grahl -- (`BUG_ADD_RELATIONSHIP`) _2012-02-08_

* (at)grahl -- (`BUG_ADD_RELATIONSHIP`) _2012-02-09_

* (at)grahl -- (`BUG_ADD_RELATIONSHIP`) _2012-10-29_

* (at)grahl -- (`BUGNOTE_ADDED`) _2012-10-29_

* (at)grahl -- (`NORMAL_TYPE`) _2013-04-24_

* (at)grahl -- (`NORMAL_TYPE`) _2013-04-24_

* (at)ruch -- (`NORMAL_TYPE`) _2013-04-24_

* (at)ruch -- (`NORMAL_TYPE`) _2013-05-06_

* (at)grahl -- (`NORMAL_TYPE`) _2013-12-06_

* (at)grahl -- (`BUGNOTE_ADDED`) _2013-12-06_

* (at)grahl -- (`NORMAL_TYPE`) _2013-12-06_

* (at)rbubel -- (`BUGNOTE_ADDED`) _2013-12-06_

* (at)rbubel -- (`BUGNOTE_ADDED`) _2013-12-06_

* (at)most -- (`BUGNOTE_ADDED`) _2013-12-06_

* (at)rbubel -- (`BUGNOTE_ADDED`) _2013-12-07_

* (at)most -- (`BUGNOTE_ADDED`) _2013-12-07_

* (at)most -- (`FILE_ADDED`) _2013-12-07_

* (at)most -- (`BUGNOTE_ADDED`) _2013-12-09_

* (at)most -- (`BUGNOTE_ADDED`) _2013-12-09_

* (at)rbubel -- (`BUGNOTE_ADDED`) _2013-12-09_

* (at)most -- (`BUGNOTE_ADDED`) _2013-12-09_

* (at)rbubel -- (`BUGNOTE_ADDED`) _2013-12-10_

* (at)mulbrich -- (`BUGNOTE_ADDED`) _2013-12-10_

* (at)mulbrich -- (`BUGNOTE_ADDED`) _2013-12-10_

* (at)rbubel -- (`BUGNOTE_ADDED`) _2013-12-10_

* (at)grahl -- (`BUGNOTE_ADDED`) _2013-12-10_

* (at)most -- (`BUGNOTE_ADDED`) _2013-12-11_

* (at)grahl -- (`BUGNOTE_ADDED`) _2013-12-11_

* (at)grahl -- (`NORMAL_TYPE`) _2014-10-13_

* (at)grahl -- (`BUGNOTE_ADDED`) _2014-10-13_

* (at)grahl -- (`NORMAL_TYPE`) _2014-10-13_

* (at)rbubel -- (`BUGNOTE_ADDED`) _2014-10-13_

* (at)mulbrich -- (`BUGNOTE_ADDED`) _2014-10-13_

* (at)rbubel -- (`BUGNOTE_ADDED`) _2014-10-13_

* (at)mulbrich -- (`BUGNOTE_ADDED`) _2014-10-13_

* (at)rbubel -- (`BUGNOTE_ADDED`) _2014-10-13_

## Attributes

* Category: Code Quality
* Status: ACKNOWLEDGED
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: LOW
* Reproducibility: NOTAPPLICABLE
* Platform: 
* Commit: 8b2a556a264885b387473bcef2aefdc7715a2d1e
* Build: 
* Tags []
* Labels:  ~Bug  ~LOW  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1165)
    
----
    
Information: 
* created_at: 2017-05-29T02:47:20.304Z
* updated_at: 2020-08-25T15:18:44.871Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 1

**Comment by FliegendeWurst** [comment]
Done in #3030
