### ISSUE TITLE
instantiation of \index is broken

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#858]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/858) where the discussions are preserved.
    
----
    
* Mantis: [MT-1380](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1380)
* Submitted on: 2013-10-31 by (at)grahl
* Updated: 2013-10-31

### Description

> In JML, the keyword \index can be used in loop (in)variants to denote the implicit counter in enhanced for loops. 
> 
> The instantiation with the concrete variable in symbolic execution seems to be broken. The interactive loop invariant dialog says the invariant was true and no variant present.

### Steps to reproduce

```
Try to verify method contains() in the attached example.
```

## Files

  
[Set.java](/uploads/3a723cf59c60ea7b239be1bf8fd7dfe8/Set.java)
  

## History

* (at)grahl -- (`NEW_BUG`) _2013-10-31_

* (at)grahl -- (`FILE_ADDED`) _2013-10-31_

## Attributes

* Category: Prover Core
* Status: NEW
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: HAVENOTTRIED
* Platform: 
* Commit: 1adaf8160e0553bdf3bac0dba004e9622d1e28d2
* Build: 
* Tags []
* Labels:  ~Prover Core  ~Bug  ~NORMAL  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1380)
    
----
    
Information: 
* created_at: 2017-05-29T02:49:47.669Z
* updated_at: 2017-05-29T02:49:47.669Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
Is provable in newer KeY version.
