### ISSUE TITLE
no progressbar during macro application

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#935]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/935) where the discussions are preserved.
    
----
    
* Mantis: [MT-1502](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1502)
* Submitted on: 2014-10-31 by (at)grahl
* Updated: 2014-11-05

### Description

> During a macro application the progress bar disappears. Only the "close provable goals" macro works. All others just display something in the status line.

## Notes

_(at)mkirsten at 2014-10-31_
> This only seems to apply to all StrategyProofMacros (e.g. for the FullInformationFlowAutoPilotMacro, the progress bar works fine).

## History

* (at)grahl -- (`NEW_BUG`) _2014-10-31_

* (at)mkirsten -- (`BUGNOTE_ADDED`) _2014-10-31_

* (at)grahl -- (`NORMAL_TYPE`) _2014-11-05_

## Attributes

* Category: GUI
* Status: NEW
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: ALWAYS
* Platform: 
* Commit: 8c7345bac74b2a019711c352f176cc5d59259949
* Build: 
* Tags []
* Labels:  ~GUI  ~Bug  ~NORMAL  
* Version: _2.4_ 

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1502)
    
----
    
Information: 
* created_at: 2017-05-29T02:51:52.071Z
* updated_at: 2017-05-29T02:51:52.071Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
Works in current KeY version
