### ISSUE TITLE
Delayed Cut crashes

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#943]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/943) where the discussions are preserved.
    
----
    
* Mantis: [MT-1160](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1160)
* Submitted on: 2012-01-24 by (at)mulbrich
* Updated: 2012-11-23

### Description

> When applying the new "Delayed Cut" feature, replaying the proof fails and one is left with a crippled proof stump.
> 
> Apparently a skolem symbol is created a second time.

### Steps to reproduce

```
- Load the attached Java file.
- Choose the PO for the only method
- Hit Autorun - it will not close since the spec is incorrect.
- Select the root sequent node
- Right Mouse Button on it -> Delayed Cut
- Enter true and press ok.

```

### Additional Information

```
Stacktrace:

(class java.lang.RuntimeException)
java.lang.RuntimeException: The cut could not be processed successfully. In order to preserve consistency the proof is pruned. For more information see details or output of your console.
	at de.uka.ilkd.key.gui.KeYMediator$6.eventException(KeYMediator.java:1008)
	at de.uka.ilkd.key.proof.delayedcut.DelayedCutProcessor.run(DelayedCutProcessor.java:402)
	at java.lang.Thread.run(Thread.java:636)
Caused by: java.lang.RuntimeException: Name already in namespace: sk_0
	at de.uka.ilkd.key.logic.Namespace.addSafely(Namespace.java:117)
	at de.uka.ilkd.key.rule.TacletApp.registerSkolemConstants(TacletApp.java:725)
	at de.uka.ilkd.key.proof.Goal.apply(Goal.java:599)
	at de.uka.ilkd.key.proof.delayedcut.DelayedCutProcessor.apply(DelayedCutProcessor.java:301)
	at de.uka.ilkd.key.proof.delayedcut.DelayedCutProcessor.rebuildSubTrees(DelayedCutProcessor.java:277)
	at de.uka.ilkd.key.proof.delayedcut.DelayedCutProcessor.cut(DelayedCutProcessor.java:125)
	at de.uka.ilkd.key.proof.delayedcut.DelayedCutProcessor.run(DelayedCutProcessor.java:399)
	... 1 more

```

## Files

  
`A.java`:

```java
class A {
 
    /*@ public normal_behaviour
      @  // requires a.length >= 1;   
      @  ensures (\forall int i; 0<=i&&i<a.length; \result >= a[i]);
      @  ensures (\exists int i; 0<=i&&i<a.length; \result == a[i]);
      (at)*/
    int getMax(int[] a) {
	int max = a[0];
 
	/*@ loop_invariant
	  @   1<=k && k<=a.length &&
	  @   (\forall int i; 0<=i&&i<k; max >= a[i]) &&
	  @   (\exists int i; 0<=i&&i<k; max == a[i]);
	  @ decreases a.length - k;
	  (at)*/
	for(int k=1; k<a.length; k++) {
	    if(max < a[k]) {
		max = a[k];
	    }
	}
 
	return max;
    }
}

```

## Notes

_(at)mulbrich at 2012-08-01_
> Unfortunately, Benjamin has left the group.
> 
> However, he has left clear instructions in the corresponding piece of code
> explaining how to fix this issue.

_(at)grahl at 2012-11-23_
> For the 2.0 release, delayed cut (and joining) will be marked as experimental and hidden from the user by default.

## History

* (at)mulbrich -- (`NEW_BUG`) _2012-01-24_

* (at)mulbrich -- (`FILE_ADDED`) _2012-01-25_

* (at)niederma -- (`NORMAL_TYPE`) _2012-01-27_

* (at)niederma -- (`NORMAL_TYPE`) _2012-01-27_

* (at)grahl -- (`NORMAL_TYPE`) _2012-08-01_

* (at)grahl -- (`NORMAL_TYPE`) _2012-08-01_

* (at)mulbrich -- (`NORMAL_TYPE`) _2012-08-01_

* (at)mulbrich -- (`BUGNOTE_ADDED`) _2012-08-01_

* (at)mulbrich -- (`NORMAL_TYPE`) _2012-08-01_

* (at)mulbrich -- (`NORMAL_TYPE`) _2012-08-01_

* (at)mulbrich -- (`NORMAL_TYPE`) _2012-08-01_

* (at)grahl -- (`NORMAL_TYPE`) _2012-11-23_

* (at)grahl -- (`BUGNOTE_ADDED`) _2012-11-23_

## Attributes

* Category: Prover Core
* Status: CONFIRMED
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: ALWAYS
* Platform: 
* Commit: None
* Build: 
* Tags []
* Labels:  ~Prover Core  ~Bug  ~NORMAL  
* Version: _2.0_ 

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1160)
    
----
    
Information: 
* created_at: 2017-05-29T02:52:01.976Z
* updated_at: 2017-05-29T02:52:02.307Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by mattulbrich** [comment]
Delayed Cuts have discontinued some time ago.
