### ISSUE TITLE
Proof loading fails sometimes probably due to indeterministic OSS

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#956]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/956) where the discussions are preserved.
    
----
    
* Mantis: [MT-1317](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1317)
* Submitted on: 2013-06-17 by (at)stijn
* Updated: 2013-06-17

### Description

> The proof loading fails sometimes. One observable issue is that the number of proof rule steps done by the OSS differ between the original proof and the (failed) loaded proof. A possible reason could be an indeterminism in the OSS. But that might also just be a symptom.
> 
> 

## History

* (at)stijn -- (`NEW_BUG`) _2013-06-17_

* (at)stijn -- (`BUG_ADD_RELATIONSHIP`) _2013-06-17_

## Attributes

* Category: Proof Loading/Saving
* Status: NEW
* Severity: MAJOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: RANDOM
* Platform: 
* Commit: 3fc4e57d2d752d55659e023364239bf2596e82a3
* Build: 
* Tags []
* Labels:  ~Proof Loading/Saving  ~Bug  ~NORMAL  
* Version: _2.0_ 

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1317)
    
----
    
Information: 
* created_at: 2017-05-29T02:52:19.955Z
* updated_at: 2017-05-29T02:52:19.955Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
There has been some work in this area, specifically limiting the view of the OSS during proof loading.
