### ISSUE TITLE
support for model methods

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#977]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/977) where the discussions are preserved.
    
----
    
* Mantis: [MT-1143](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1143)
* Submitted on: 2011-12-06 by (at)grahl
* Updated: 2013-07-04

* Assigned to: (at)most

### Description

> With model methods many current problems at the specification level will be solved.

## Notes

_(at)grahl at 2012-10-12_
> After the recent discovery of an already working implementation, this issue should be closed.

_(at)most at 2012-10-12_
> No, because it is not (yet) fully working. I would love to finish it and make it available, just not sure I can do it before the feature freeze on Oct. 31st.

## Associated Bugs

* Relates to MT-1329 with 

* Relates to MT-1462 with 

## History

* (at)grahl -- (`NEW_BUG`) _2011-12-06_

* (at)grahl -- (`BUG_ADD_RELATIONSHIP`) _2011-12-06_

* (at)grahl -- (`BUG_ADD_RELATIONSHIP`) _2011-12-06_

* (at)grahl -- (`BUG_DEL_RELATIONSHIP`) _2012-10-12_

* (at)grahl -- (`BUG_DEL_RELATIONSHIP`) _2012-10-12_

* (at)grahl -- (`BUGNOTE_ADDED`) _2012-10-12_

* (at)grahl -- (`NORMAL_TYPE`) _2012-10-12_

* (at)most -- (`BUGNOTE_ADDED`) _2012-10-12_

* (at)grahl -- (`NORMAL_TYPE`) _2012-10-15_

* (at)grahl -- (`NORMAL_TYPE`) _2012-10-15_

* (at)grahl -- (`NORMAL_TYPE`) _2012-10-15_

* (at)grahl -- (`NORMAL_TYPE`) _2012-11-23_

* (at)grahl -- (`BUG_ADD_RELATIONSHIP`) _2013-07-04_

* (at)grahl -- (`BUG_ADD_RELATIONSHIP`) _2013-12-06_

* (at)grahl -- (`NORMAL_TYPE`) _2014-01-03_

* (at)grahl -- (`BUG_ADD_RELATIONSHIP`) _2014-06-12_

* (at)most -- (`BUG_ADD_RELATIONSHIP`) _2014-07-02_

## Attributes

* Category: JML (semantics)
* Status: ASSIGNED
* Severity: FEATURE
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: NOTAPPLICABLE
* Platform: 
* Commit: None
* Build: 
* Tags []
* Labels:  ~JML (Semantics)  ~Feature  ~NORMAL  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1143)
    
----
    
Information: 
* created_at: 2017-05-29T02:52:54.443Z
* updated_at: 2017-05-29T02:52:54.443Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by mattulbrich** [comment]
Model methods have long been implemented and are an active part of KeY's JML dialect!
